language: haskell
ghc:
  - 7.6
  - 7.8

before_install:
  - cabal install markdown-unlit

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
  - cabal install --ghc-options=-Werror
